### ISSUE TITLE
Failed to refresh download url

### ISSUE THREAD

**Issue by caldrian** [pusher/chatkit-swift#167] opened 2019-03-22 12:09 UTC
### What?

The url of an attachment cannot be refreshed due to wrong concatenation of the request url.
See the requested URL in the second line of the snippet:
```
PusherPlatform.PPRequestTaskDelegateError.badResponseStatusCodeWithMessage(response: <NSHTTPURLResponse: 0x600003c486e0> {
  URL: https://us1.pusherplatform.io/services/chatkit/v3/5f401074-b9d1-446f-8f94-3a540ba258f1/https:/us1.pusherplatform.io/services/chatkit/v3/5f401074-b9d1-446f-8f94-3a540ba258f1/rooms/19392892/attachments/d08be308-f085-44de-a5f5-9bb2430f59e0
} { Status Code: 401, Headers {
    "Content-Length" =     (
        229
    );
    "Content-Type" =     (
        "application/json"
    );
    Date =     (
        "Fri, 22 Mar 2019 12:05:18 GMT"
    );
    Server =     (
        envoy
    );
    "access-control-expose-headers" =     (
        "Access-Control-Max-Age"
    );
    "access-control-max-age" =     (
        86400
    );
    "x-envoy-decorator-operation" =     (
        http
    );
    "x-envoy-upstream-service-time" =     (
        6
    );
} }, errorMessage: "services/chatkit_authorizer/authorization/unknown_request_path: Unsupported request path")
```

The concatenation of the url happens here: https://github.com/pusher/pusher-platform-swift/blob/master/Sources/Instance.swift#L400

### Environment

* **PusherChatkit version: 1.4.3**
* **Xcode version: 10.1**
* **Swift version: 4.2**

----

**Comment by caldrian** [comment] 2019-03-28 07:44
I created a demo project which sends multipart messages with an image as attachment.
After some time (less than an hour) the attachment cannot be loaded anymore.

![Simulator Screen Shot](https://user-images.githubusercontent.com/15628584/55139285-abdcc680-5135-11e9-9c18-5740fb271e36.png)

[AttachmentRefresh.zip](https://github.com/pusher/chatkit-swift/files/3016695/AttachmentRefresh.zip)

@vivangkumar may I ask you to have a look at it, please?

**Comment by jain-ruchi** [comment] 2019-03-28 14:33
We're experiencing this issue as well! Please address! 🙏 🙏 🙏

**Comment by viczhong** [comment] 2019-03-28 18:30
Ditto!

**Comment by vivangkumar** [comment] 2019-04-01 09:24
Hi guys! My bad, I somehow didn't get notified of this and I've just seen this :( I think I know where the issue is. Fix is inbound.

**Closed** 2019-04-01 12:58 UTC
