### ISSUE TITLE
Compilation failed for PusherChatkit with Xcode 10.2 and Swift 5

### ISSUE THREAD

**Issue by ryanmusic** [pusher/chatkit-swift#237] opened 2020-01-01 02:09 UTC
### What?

After downloading PusherChatkit with 'pod install', run the project and the compilation will fail.

<img width="752" alt="Screen Shot 2020-01-01 at 10 04 21 AM" src="https://user-images.githubusercontent.com/406434/71637455-bd33a000-2c7e-11ea-9114-e9bc33ca24b2.png">
<img width="799" alt="Screen Shot 2020-01-01 at 10 04 30 AM" src="https://user-images.githubusercontent.com/406434/71637456-bd33a000-2c7e-11ea-87ce-80a767691938.png">

### Environment

* **PusherChatkit version: 
Installing PushNotifications (3.0.1)
Installing PusherChatkit (1.8.3)
Installing PusherPlatform (0.7.2)

* **Xcode version: 10.2
* **Swift version: 5
* **Platform(s) running PusherChatkit: MacOS

### Demo Project (if you have one; it helps a lot!)

----

**Comment by wonder2011** [comment] 2020-01-20 05:20
I have the same error. Any workaround for this ?. This is brokening my app compilation right now !

**Comment by wonder2011** [comment] 2020-01-20 20:21
@ryanmusic do you solve this ? Installing other branch, tag or finding another library ?

**Comment by wonder2011** [comment] 2020-01-20 22:00
@ryanmusic i use brach 1.8.2 and is working fine. If some time ago pusher fix 1.8.3 i will update !

**Comment by grzesiekko** [comment] 2020-01-21 11:16
It looks like the issue is not related to the version of Swift used by Chatkit/application, but is related to the new version of push notification API that has been introduced in iOS 13. I will try to replicate the problem and come back with a solution.

**Comment by grzesiekko** [comment] 2020-01-22 17:33
The issue has been fixed in https://github.com/pusher/push-notifications-swift/commit/7f074a47beab45ca020806c06c88e65c80a7227e (release `3.0.2`). You can update the SDK using CocoaPods (`pod update PushNotifications`) or Carthage (`carthage update push-notifications-swift`).

**Closed by grzesiekko** 2020-01-22 17:33 UTC
